kind: Secret
apiVersion: v1
metadata:
  name: gemini-secrets
  namespace: gemini
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLVJDcG1zclNoSnpkSWVScFlhRDNKNURQZG8xa24=
  NEXTAUTH_SECRET: U+wt89TgGZiVR/Xy9n7DOYjCxRXCCwCBDyJbIRCkt5w=
  NEXT_PUBLIC_API_KEY: QUl6YVN5QmpiNmFRaURwNm9sVEpva2F6Nm9JaFpJMXY3Ukpvcksw
  MONGO_INITDB_ROOT_PASSWORD: cm9vdEBhZG1pbg==